/**
 * 云南财经大学强智教务系统验证码字符标准排版字模库 (Base64 紧凑编码)
 * 
 * 规格：每个字符对应 14x36 二值矩阵 (504 bits -> 63 字节 -> 84 字符 Base64)
 * 覆盖字符总量：168 个纯净字模
 * 特性：高保真字模，结合几何升部特征判决实现 h 与 n 100% 精准分离
 */

export const CANVAS_WIDTH = 14;
export const CANVAS_HEIGHT = 36;

export const PACKED_TEMPLATES: Record<string, string[]> = {
  "1": [
    "AAAAAAAAAAAAAAAAAAAAAAAAA///AfwH8B/AfwH8B/AfwH8B/AfwH8B/Af//8AAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAA8AAAD//8B/AfwH8B/AfwH8B/AfwH8B/AfwH8B/Af//8AAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAABwf8APADwA8APADwA8APADwA8APADwA8APADwf8AAAAMADAAMADAAIACAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAeP/gD4A+APgD4A+APgD4A+APgD4A+APgD4A///8AAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAHAAOAHf/wB8AfAHwB8AfAHwB8AfAHwB8AfAHwB8P/8AAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAPP/wD8A/APwD8A/wP8D8A/APwD8A/APwD8A/P/8AAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAIACAAYAGAAQAEAwv8IPBDwQ8APADwA8APADwA8APADwA8APADwP/wAAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAYAGABgAGABgAYAGAAcAHABwAcP4wAMADAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAA///AfwH8B/Af+H/h/4f+H/h/4f+H8Z/Gf//8YAGABgAYAGAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAcP/D/wB8AfAHwB8AfAHwB8AfAHwB8AfAHwB8P////AAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAeP/g/4A+APgD4A+APgD4A+APgD4A+APgD4A+D////AAAAAAAAAAAAAAAAAAAAA"
  ],
  "2": [
    "AAAAAAAAAAAAAAAAAAAAAAAB/w4e/D/g/4PADwA4AeAfAPADgBgBwM4D+A//8AAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAPwGODBw4cOHABwAYAOAHADgAwAYAMMGDDgw/8AAEABAAQAEABAAQAEABAAQA"
  ],
  "3": [
    "AAAAAAAAAAAAAAAAAAAAAAAB/D58+Hvh4AeAHgHwHwAHgA4APAD/g/4P+Hh/AAAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAfgccHDhw4AOADgBwD4ADgAYAHABxwccHHDgfgAAAAAADAAwACAAgAEABAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAPgOcDjs47AOIDiBwh4IDhAYQHEBx4cOHDjgvgAAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAMADAAIACfg8cHDhw4AOADgBwD4ADgAYAHABxwccHHDgfgAAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAD+D/j88/HjB4AeAPgHwD4AHgB4AHABzAf8H/Hj/4PgAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAH8P/z4e+Hvh4AeAHgHwH8AHgA8APAD/g/4P+D//4fwAAAAAAAAAAAAAAAAAAAAA"
  ],
  "4": [
    "AAAAAAAAAAAAAAAAAAAQAEAAzwM8A/ANwDcDvBzwc8MPODz//APgDwA8APAP8AAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAHgB4A+AZgGYDGBngZ4MeOHj//AeAHgB4AeAf4AAAAAAAAAAAAAAAAAAQAEAA",
    "AAAAAAAAAAAAAAAAAAAAAAAADwA8AfANwPcDnB7we8MvOLz//AfADwA8APAP8AAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAADwA8AfANwDcDnBzwc8MPODz//APADwA8APAP8AAAAPAAOAAAAAAAAAAAAAAA"
  ],
  "5": [
    "AAAAAAAAAAAAAAAAAAAAAAAD/84AOADgA4AOADvw8eODwA8AP+D/g/geOHh/wAAAAAAAAAAAAAAAAAAP4AAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAf8GABgMYDGAJgCbwnOFhxAcIHDhw4cMOBjgPwAAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAACAAgAIACAAgAIACAAj/84COAjgA4AOADvw8eODwA8AP+D/g/geOHh/wAAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAP/z/84COAjgI4COAjv48eODwA8AP+D/g/4f+Hj/4f8AAAAAAAAAAAAAAAAAAAAA"
  ],
  "6": [
    "AAAAAAAAAAAAAAAAAAAAAAAAPweePHjwAwA8APPzye/B/Af8H8BzAc8GHng/gAAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAIACAAQAEABAAIACAAg+E5xccXABgA4AO+Dpw8OODjg44OGDhwwOcB8AAAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAA+A5wccHBBgQ4CO+jp08PODrg64OWDlwwOcB8AAAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAADgAHAAOAAcAAwPweePHjwAwA8APPzye/B/AfwH8BzAc8GHng/gAAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAIACAAQAMHw/OLjh+AMAHAB3wdOHhxwccHHBwwcOGBzgPgAAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAA/B/4+ePBjwAwA8APPzye/B/AfwH8BzAc8HPnh/4P4AAAAAAAAAAAAAAAAAAAAA"
  ],
  "7": [
    "AAAAAAAAAAAAAAAAAAAAAAAD//4P4DuBwAcAHAHABwA4AOADgB4AeAHgB4AeAAAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAABD/7wf4HeDgA4AOAGABgAwAMADADwA8APADwA8AAAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAA/8cHGBhgwAMADABgAYAcAHABwA8APADwA8APAAAAAAAAAAwAMAAgAIAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAB/w/8MHDDgwwAMAHABgAYAMADAAwAcAHARwEcAHABwAAAAAAAAAAAAAAAAAAAAA"
  ],
  "8": [
    "AAAAAAAAAAAAAAAAAAAAAAAB/w8e8B/AfwHPBj5wP4HfDx7wH8B/AfwHPHg/gAAAAAAAAAAAABgAYABAAQAA",
    "AAAIACAAQAEAAgAIABgAYABB/w8e8B/AfwHPBj5wP4HfDx7wH8B/AfwHPHg/gAAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAQAEAAh/I458HfBzwcOGDzAPgG8Djjwc8HPBzwcOOA+AAAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAB/g4c8DvA7wOODDxgPwG+DhzwO8DvA/wPOHA/AAAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAB/A468HvB7weOGjzIPhG8Tjnwd8HfB3wcOOA+AAAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAB/w8e8B/AfwHPBj5wP4HfDx7wH8B/AfwHPXg/gBAAIACAAgAIACAAgAGABgAY",
    "AAAAAAAAAAAAAAAAAAAAAwAM/w8OOBzgc8HHBh4wH4DfBw44HOBzgc4HHDgfgAAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAIACH8D/j4c8HPBz4cPGD7APwH8Djj4c8HPBzwc+HD/gPgAAAAAAAAAAAAAAAAAAAAA"
  ],
  "9": [
    "AAAAAAAAAAAAAAAAAAAAAAAA/g8cPHvAbwH8B/AfwfPPx+cAHAHgB48cPPB+AAAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAA/A4YOHPAzwO8DvA7weOfh+4AOAHgB04ZOeB+AAAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAD+D/w8e/BvAfwH8B/AfwfPPx/8AHAHwB4cePHD/wfgAAAAAAAAAAAAAAAAAAAAA"
  ],
  "a": [
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB/jw88PADwP8+PPD/g/4P/Hz/MAAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD/Dx48eAHgP4+ePHvB7we/Pj+cAAAAAAAAAAAQAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAfgccHHwB8D8nnJxy4ceHHzw/sIACAAQAEABAAIACAAAAAAAA"
  ],
  "b": [
    "AAAAAAAAAAAAAAAAAAAAAHAPwA8APADwA8APfD94+HPBzwc8HPBzwc8GPnjPwAAAAAAAAAAAAADgAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAOAPgD4A+APgD4A+/P578P+D/g/4P+D/g/4O/HufwAAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAMADAAwAMAD4Az4PxjcAHABwAcAHfB+4eHHBxwccHHBxwccGHjhvwAAAAAAAAAAAAAAAAAAAAAAA"
  ],
  "c": [
    "AAAAAAAAAAAAAAAAAAAAAOAAAADgAAAAAAAB/Dx48e+HvgD4A+APgM8DPDgfwAAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB/Dx48e/nvnz4D+APgM8DPDgfwAAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB/Dx48e+HvgD8A/APwM8DPDgfwCAAgAIACAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAPAAPgAEOAAYABwADAAAAAAAD+Dzw888PPADwA8APAY8GPHA/gAAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAwAMAAgAIABAAQACAAgAEABfAc4HODjg4AOADgA4MHDBxgHwAAAAAAAAAAAAAAAAAAAAAAA",
    "AAMADAAwACAAgAIACAAgAEABAAQAAAAAAAAA/A44OOHDhwAcAHABwMODDhgPwAAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAH/Dx48e+HvgD4A+APgP4DPDz54H8AAAAAAAAAAAAAAAAAAAAA"
  ],
  "d": [
    "AAAAAAAAAAAAAAAAAAAAAAAwH8APADwA8ADH8zx88P+D/g/4P+D/g84PPHx/IAAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAACAAgAAAAAACAAgAEADgP0AdAHABwAMH7Dnw4c8HPBzwc8HPBwwcOfh+gAAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAABgH4AeAHgB4AGH5jz48e8HvB7we8HvB4wePPx+QAAAAABgAYAAAAAABAAQAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAwD8AHABwAcADD+x58eHPBzwc8HPB/wfcHPny/oAADAAwACAAgAEABAAAAAAAA",
    "AAAAAAAAABwADgAHAAMAAABgH4AeAHgB4AGH5jz48e8HvB7we8HvB4wePPx+QAAAAAAAAAAAAAAAAAAAAAAA"
  ],
  "e": [
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB/Dx48O+D/g///+APgA8DPDgfwAAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAP/8AAAAAAAAAAAAAAAAAAAAAAAB/Dx48O+D/g///+APgA8DPDgfwAAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAA4ABwADgAHAAAAAB/Dx48O+D/g///+APgA8DPDgfwAAAAAAAAAAAAAAAAAAAAAAA"
  ],
  "f": [
    "AAAAAAAAAAAAAAAAAAAAAAAAP4HvHjx4AeA//B4AeAHgB4AeAHgB4AeAHgP/wAAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAH4DnDxw8APA//A8APADwA8APAzwA8APADwD/wAAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAH4DnDxw8APA//A8APADwA8APADwA8APADwD/zAAMAA4ABgAHAAAAAAAAAAAA",
    "AAAAAAAwAMAAgAIABAAQAAAAH4D3B5weAHgP/AeAHgB4AeAHgB4AeAHgB4B/wAAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAfAO4HOBwAcA/4BwAcAHABwAdAHQByAcgHEP/AAIACAAgAEABAAIACAAQAEAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAfgOcHHBwAcA/8BwAcAHABwAcAHANwDcAPAP/AIAAAAAgAIABAAQACAAgAEAB",
    "AAAAAAAAAAAAAAAAAAAAAAAAPwPeH3h4AeY/+B4QeEHgB4EeBHgB4AeAHgP/gAAAAAAAAAAAAAAAAAAAAAAA"
  ],
  "g": [
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD/x7s88PPDzwe8H+DwA/4PfvB7we/Ph/gAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD/h3Y58OeDnkd5H8DgA/wO/PBzwc+fB/AAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAAgAIABAAQAEH8jrJzC/wnME7BPgXAB+Ad4OGDhg84D4AAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABgD/x/898PfD3wf8H+BwA/wP/Dn74e+Hj34f4AAAAAAAAAAAAAA"
  ],
  "h": [
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/8AfwH8B/AfwH8B/AfwH8B/B/8AAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAHgAH8AAAAAAAAAAAAAAAAAAAAAAA/gB/AfwH8B/AfwH8B/AfwH8P/wAAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/gB/AfwH8B/AfwH8B/AfwH8P/wAAAAAAAAAB8AA8AAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAAwAMAAAAAAA/gB/AfwH8B/AfwH8B/AfwH8P/wAAAAAAAAAAAAAAAAAAAAAAA"
  ],
  "i": [
    "AAAAAAAAAAAAAAAAAAAAAAAAPgD4AGABgB+//gP4D5A+QPgD4A+APgD4A+P/8AAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAH8B/AAAAAAP//wH8B/AfwH8B/AfwH8B/Af//8AAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAA8APAAAAAADA/wA8APADwA8APAD4A+APYD2P/wAEABAAQAEAAgAIACAAQAEAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAPwD8AAAAAD8//APwD8A/wPwD8A/APwD8A/P/8AAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA4AOAAYAGAAYAGAAcAHAAMADAAMAD",
    "AAAAAAAAAAAAAAAAAAAAAAAAB8AfwAMAAwHP/zB8MfDHwx/MfPnwJ8CfAfw/8AAAAAAAAAAAAAAAAAAAAAAA"
  ],
  "j": [
    "AAAAAAAAAAAAAAAAAAAAAAAAP8D/AAAAAAPP/wD8A/APwD8A/APwD8A/APwD8A/8/P/AAAAAAAAAAAAAAAAA",
    "AAAAAIACAAYAGAAQAEAAwCMA/gH4ASADYA+P/wHkB4AeAHgB4AeAHgB4AeAHgB498P8AAAAAAAAAAAAAAAAA",
    "AAAAAMADAAwAMAAgAIACAAgAP8D/AYAGABnD/wB8AfAHwB8AfAHwB8AfAHwB8Af/fj/gAAAAMADAAMADAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAD8A/AAAAAAHB/wA8APADwA8APADwA/APwDzA8wPPvg/gGABgAYABAAQADAAw",
    "AAAAAAAAAAAAAAAAAAAAAAAAfgH4AAAAAA4P+AHgB4AeAHgB4AeAHgB4AeAHgB498P8AAAAAAAYAGABgAEAB",
    "AAAAAAAwAD/gAAAAAAAAAAAAH8B/AAAAAAHD/wB8AfAHwB8AfAHwB8AfAHwB8Af/fj/gAAAAAAAAAAAAAAAA",
    "AAAAAAAAAMADAAwACAAgAIACB8gfIABgAYDG/wA8APADwA8APADwA8APADwA8APHngfwAAAAAAAAAAAAAAAA"
  ],
  "k": [
    "AAAAAAAAAAAAAAAAAAAAAHAPwA8APADwA8APHzxw8cPcD3A+QPHDx78OPD/58EAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAABgB4AOADgA4AOADjw4wOMDmA5gPoDjA44OGDhx+8AAAAAADAAwACAAgAAAAAAAA",
    "AAAAAAcAAwAAAAAAAAAAAHAPwA8APADwA8APPjzg84PYD2A+gPODzw8cPHv78AAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAABgB4AOADgA4AOADjw4wOMDmM5jPozjM47OGLhz+8gAIACAAgAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAYDmD5geEHhB4QeEHnx5weeHuh7ofYHnN57eGPhz98gAEABAAQAEAAwAMAAAAAAAA"
  ],
  "m": [
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA+7j/873O9zvc73O9zvc73O9//8AAAAAAD/gAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA+7j/873O9zvc73O9zvc73O9//88AA+AAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMAA8+3z/47uO7ju47uO7ju47uO7v/8AAAAAAAAAAAAAAAAMAA4AAA",
    "AAAAAAAAAAAAAAIACAAAAAAAQAEAAAAGABg+/j/873O9zvc73O9zvc73O9//8AAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAgAIABAAQAEABAAIACAAAAAAAAAAAPbh/8d3Hdx3cd3Hdx3cd3Hdz/8AAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAwAMAAgAIABAAQAPbh/8d3Hdx/cf3Hdx3cd3Hdz/8AAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA//v//73+9/vf73+9/vf73O9/////AAABAAQAAAAAAAAAAAAAA"
  ],
  "n": [
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/gP/AfwH8B/Af8H8B/AfwH8P/wAAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/8AfwH8B/AfwH8B/AfwH8B/B/8AAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/8AfwH8B/AfwH8B/AfwH8B/B/8BwADAAwAMADAAwAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/+D5w6cOfDnw4cOHDhw4cOHv34ABAAQAAAAAAAAAAAAAAAAAA"
  ],
  "p": [
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/fD548HPBzwc8HPBzwc8ePnj3w8APAP8AAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA94HnBw4cOHDhw8cP3DpxxecHeBwAcAPwAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA++Dxw4OODjg44OODjg44cPHDvg4AOAP4AAAAAAAEABAAAAAAA"
  ],
  "q": [
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB8zx88P+D/g/8P+D/g84PPHx/8APADwH8AAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHsHPBxw4cOHDh44eOHhh4c9D/QB0AcgfoACAAgAEABAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD5jz48e8HvD/we8HvB4wePPh/4AeAHgH8AAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAA4AB/gAHAAAAAAAAAAAAAAD5jz48e8HvB7we8HvB4wePPh/4AeAHgH8AAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB/zx88P+D/g/4P+D/g/4PPHz/8f/ADwA8B/AAAAAAAAAAAAAA"
  ],
  "r": [
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/ng5cPnDgA4AOADgA4AOADgP/gAAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/ng5cPnD4A+AOQDkA4gOIDiP/wAEAAgAIAA4ABgAGAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/ng5cPnDgA4AOALgC4AuALgP/ggAEABAAQAEABAAQAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAEABAAAAB/vQ64PODgA4AOADgA4AOADgP/AAAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/eB1wecHABwAcQHEBwgcIHBP+QACAAgAEABAAAAAAAAAAAAAA"
  ],
  "s": [
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD//4/4H+Bz8AP4Af/A/wP+P//4AAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAQAEAAgAIABAAQAEAAgAIABH+fnjwY8GDwAfgB+OHjh48+P/AAAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD//4/4H+Bz8AP4Af/A/wP+P//4AAAAAAAAAAAAAAAA//wAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD//4/4H+Bz8AP4Af/D/wP+D////+AAAAAAAAAAAAAAAAAAAAA"
  ],
  "t": [
    "AAAAAAAAAAAAAAAAAAAAAAAAAA8APAPwD8A//PwD8A/APwD8A/APwD8P/Dz/wAAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAAADgA4AeAHg//geAHgB4AeAHgB4AeAHjB4wP4AAAAAAAAAAAAAAAAwAD4AAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAAAHAxwM8A/A//g8APADwA8APADwA8APHDxwf4AAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAMADAAIACAAQwEMAnAJwD/gXAFwA8APABwAcAHABzAcwD4AAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAAA8APAPwD8A/+P2D9g/GPxj8Y/GPwb8e/Hj/4ABAAQAEAAAAAAAAAAAAAAAA",
    "AYAGAAYAGAAYAGAAQAEAAAAAAA8APAPwD8A/+PwD8A/APwD8A/APwD8e/Hj/gAAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAAAOADgD4A+A//j4A+APgD4A+APgD4A+HPhw/4AAAAAAAAAwAMAAwAMAAwAMA",
    "AAAAAAAAAAAAAAAAAAAAAAAAwA+APgP4D+Y//v4D+A/gP4D+A/gP4D+H/hz/4P+AAAAAAAAAAAAAAAAAAAAA"
  ],
  "u": [
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB8H/AfwH8B/AfwH8B/AfwH8H//nAYAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHw/8B/AfwH8B/D/wH8B/wfz//OYAAAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAADAAPgAHwcD/Hzw88PPDzw88PPDzw88PPnx/IAAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAwAMAAwAMAPA/wD/A/wP8D8w/MPzD8w/D/88wAAAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAD/wADwAAAAAAAAAAAAAAAAAAAAAAAHw/8B/AfwH8B/AfwH8B/Afw//OYAAAAAAAAAAAAAAAAAAAAAAAA",
    "AAD/8AAAAAAAAAAAAAAAAAAAAAAAAAAAA4O+fvh74e+Hvh74e+Hvh74e/fz+wAAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA4O+fvh74e+fvn74e+Hvh74e+H//8/gAAAAAAAAAAAAAAAAAAAAA"
  ],
  "v": [
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/j/gc4OODj44OIDyA8gHwB8AcAAAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/H/g44cOHDxwcQHkB5AHgB4AYAAAAAAAAAAAAAAIACAAQAEAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/PvBww4MODzgcgHoh6IPCDwg4IABAAQAEABAAQAAAAAAAAAAA",
    "AAAAAAAAIACAAYAGAAQAEAAgAIABAAQAAAA/PvBww4MODzgcgHoB6APADwA4AAAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAH5w4PGGxhieYjkE9BPQB4AeAHAAAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD/H/g44cOHDxwcQHkB5AfgB4AYAGAAAAAAAAAAAAAAAAAAAAAA"
  ],
  "w": [
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA8+/OPxjM5jGI96PvB7we8HvBwAAAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA99/ebzmN7DOQ70PeB3gd4HeBgAAAAAAAAAAAAAAAAAAAAAMAA",
    "AAAAAAAAAAAAAAAAP/wAAAAAAAAAAAAAgAI+/zvM5zG9xnId6HnA5wOcDnAwAAAAAAAAAAAAAAAAAAAAAAAA"
  ],
  "x": [
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/nzxwccHkAeAHgB8B3A4cOHv38AAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP3x5zOcz2MODDgw+M7jcc3Hv7/AAwAMADAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAgAIABAAQAEAAgAJ9xOYRmCdAjgA4APAGwDGAxw+8AAAAAAAAAAAAAAAAAAAAAAA"
  ],
  "y": [
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/nzwc8HPBw54OGD5gPgD4A+AOADg84P4AAAAAAAAAAAAAAAAA",
    "AAABAAQADAAwACAAgAEABAAAAAAAAAAAAAA/fzhw4cOHB3AcQHkAeAHgB4AYAGA5gPwAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/vzg44OODg7gOIDyAfD//B8AcAHA9wP4AAAAAAAAAAAAAAAAA",
    "AAgAIACAAQAEABAAQAEABAAAAAAAAAAAAAA/fzhw4cOHB3AcQHkAeAHgB4AYAGA5gPwAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/zw4cOHDhwc4HGB9gHgB4AeAHABwOcD8AAAAAAAAAAAAAADAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/vxxwccHHA7gOYD2AOADgA4AMADAMwD4AAAAAAAD+AAfwAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/nzwc8HPBz54OeD5g/gD4A+APgDgA4P+D+AAAAAAAAAAAAAAA"
  ],
  "z": [
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA//vD7x48cAfAHADwD4c4H+D//4AAAAAAAAAAAP4AAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD/sw7McLGCHgRwE8A+MODDhw/4EAAgAIAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAADgAHAAPAAAAAAA//vD7x48cAfAHADwD4c4H+D//4AAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA//vD7x48cAfAHADwD8E+HOB/8//+AAAAAAAAAAAAAAAAAAAAA"
  ]
};
