/**
 * 云南财经大学强智教务系统验证码字符标准排版字模库 (Base64 紧凑编码)
 * 
 * 规格：每个字符对应 14x36 二值矩阵 (504 bits -> 63 字节 -> 84 字符 Base64)
 * 覆盖字符总量：114 个纯净字模
 */

export const CANVAS_WIDTH = 14;
export const CANVAS_HEIGHT = 36;

export const PACKED_TEMPLATES: Record<string, string[]> = {
  "1": [
    "AAAAAAAAAAAAAAAAAAAAAAAAHwf8B/AfwH8B/AfwH8B/AfwH8B/AfwH8B/B/8AAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAB8P/AfwH8B/AfwH8B/AfwH8B/AfwH8B/AfwH///8AAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAHz/85/Ofwf8H/B/wf8B/AfwH8B/AfwH8B/B/8AAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAfAfP/wH8B/AfwH8B/AfwH8B/AfwH8B/AfwH8P/wAAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAA8H/AfwH8B/AfwH8B/Af+H/h/4f+H8Z/Gf//8YAGAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAcP/D/wB8AfAHwB8AfAHwB8AfAHwB8AfAHwB8P////AAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAeP/g/4A+APgD4A+APgD4A+APgD4A+APgD4A+D////AAAAAAAAAAAAAAAAAAAAA"
  ],
  "2": [
    "AAAAAAAAAAAAAAAAAAAAAAAB/w4e/D/g/4PADwA4AeAfAPADgBgBwM4D+A//8AAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAA/wceMBzwc8HABwAYAeAPAHgBgAwA4McDPAz/8AAAAAAAAAAAAAAAAAAAAAAA"
  ],
  "3": [
    "AAAAAAAAAAAAAAAAAAAAAAAB/D58+Hvh4AeAHgHwDwAHgA4APAD/g/4P+Hh/AAAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAfgccHDhw4AOADsBzB4wDiAYgHIBzwccHHDhfgAAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAM/j88PHjx4AeAHgDwB4AHgAYAHABzwc8HPHg/gAAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAD+D/j88/HjB4AeAPgHwD4AHgB4AHABzAf8H/Hj/4PgAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAH8P/z4e+Hvh4AeAHgHwD8AHgA8APAD/g/4P+D//4fwAAAAAAAAAAAAAAAAAAAAA"
  ],
  "4": [
    "AAAAAAAAAAAAAAAAAAAAAAAAR4EeA/gO4DuBnhx4ceOHuB7//AHwB4AeAHgH8AAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAHgB4A+AZgGYDGBnwZ6MeuHn//AeAHgB4AeAPwAAAAAAAAAAAAAAAAAAAAAAA"
  ],
  "5": [
    "AAAAAAAAAAAAAAAAAAAAAAAD/A4AOADgA4AOADvw8eODwA8AP+D/g/geOHh/wAAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAA/gMADAAwAMADAM3zOOLByAcQHHBxwcYODDgfwAAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAP/z/84COAjgI4COAjv48eODwA8AP+D/g/4f+Hj/4f8AAAAAAAAAAAAAAAAAAAAA"
  ],
  "6": [
    "AAAAAAAAAAAAAAAAAAAAAAAAPweePHjwAwA8APPzye/B/Af8H8BzAc8GHng/gAAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAA+A5wccHABgA4AO+Dpw8OODjg44OGDhwwOcB8AAAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAfAc4OODggwI8BPfT06+HvB3wd8HDBw4YHOA+AAAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAwAMHw/OLjh8AMAHAB3wdOHhxwccHHBwwcOGBzgPgAAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAA/B/4+ePBjwAwA8APPzye/B/AfwH8BzAc8HPnh/4P4AAAAAAAAAAAAAAAAAAAAA"
  ],
  "7": [
    "AAAAAAAAAAAAAAAAAAAAAAAD//4P4DuBwAcAHAHABwA4AOADgB4AeAHgB4AeAAAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAABD/7wf4HeDgA4AOAGABgAwAMADADwA8APADwA8AAAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAP////gP4HuBwAcAfAHABwA4AOADgB4AeAHgB4AeAHgAAAAAAAAAAAAAAAAAAAAA"
  ],
  "8": [
    "AAAAAAAAAAAAAAAAAAAAAAAB/w8e8B/AfwHPBj5wP4HfDx7wH8B/AfwHPHg/gAAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAB/g4c8DvA7wOODDxgPwG+DhzwO8DvA/wPOHA/AAAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAB/A468HvB7weOGjzIPhG8Tjnwc8HPBzwcOOA+AAAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAH/D/78H8B/Af8HPhj9wP8H/Dx78H8B/AfwH/Bz/4P4AAAAAAAAAAAAAAAAAAAAA"
  ],
  "9": [
    "AAAAAAAAAAAAAAAAAAAAAAAA/g8cPHvAbwH8B/AfwfPPx+cAHAHgB48cPPB+AAAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAD+D/w8e/BvAfwH8B/AfwfPPx/8AHAHwB4cePHD/wfgAAAAAAAAAAAAAAAAAAAAA"
  ],
  "a": [
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB/jw88PADwP8+PPD/g/4P/Hz/MAAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD/Dx48eAHgP4+ePHvB7we/Pj+ccAA4AB4ABAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/g4cOHABwH8Pnzh9wc8HPjx/sQAEAAgAIAAAAAAAAAAAAAAA"
  ],
  "b": [
    "AAAAAAAAAAAAAAAAAAAAAOAPgD4A+APgD4A+/P578P+D/g/4P+D/g/4O/HufwAAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAHAPwA8APADwA8APfD94+HPBzwc8HPBzwc8GPnjPwAAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAwAMAD4AzgPwDcAHABwAcAHfB+4eHHBxwccHHBxwccGHjhvwAAAAAAAAAAAAAAAAAAAAAAA"
  ],
  "c": [
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB/Dx48e+HvgD4A+APgM8DPDgfwAAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAMADAAIACAAQAE/B54eePHjwA8APADwMeDHhgPwAAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAH/Dx48e+HvgD4A+APgP4DPDz54H8AAAAAAAAAAAAAAAAAAAAA"
  ],
  "d": [
    "AAAAAAAAAAAAAAAAAAAAAAAwB8APADwA8ADH8zx88P+D/g/4P+D/g84PPHx/IAAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAACABwD4AeAHgB4AGH5jz48e8HvB7we8HvB4wePPx+QAAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAwB8AHABwAcADD+x58eHPBzwc8HPB/wfcHPny/oAAAAAAAAAAAAAAAAAAAAAAA"
  ],
  "e": [
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB/Dx48O+D/g///+APgA8DPDgfwAAAAAAAAAAAAAAAAAAAAAAA"
  ],
  "f": [
    "AAAAAAAAAAAAAAAAAAAAAAAAH8H8H8B/Afw//B/AfwH8B/AfwH8B/AfwH8P/wAAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAA8B/B/AfwH8H/wfwH8B/AfwH8B/AfwH85/P/8GAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAf4PPPjz4A+A/wD4A+APgD4A+APgD4A+AP8P/gAAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAfweePHjwA8A/gDwA8APADwA8APADwA8QPDP/wACAAgAIABAAQAAAAAAAAAAA"
  ],
  "g": [
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD/x7s88PPDzwe8H+DwA/4PfvB7we/Ph/gAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABgD/x/898PfD3wf8H+BwA/wP/Dn74e+Hj34f4AAAAAAAAAAAAAA"
  ],
  "h": [
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/8AfwH8B/AfwH8B/AfwH8B/B/8AAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/gB/AfwH8B/AfwH8B/AfwH8P/wAAAAAAAAAAAAAAAAAAAAAAA"
  ],
  "i": [
    "AAAAAAAAAAAAAAAAAAAAAAAB/AfwAcAHAH8//B/wfwH8B/AfwH8B/AfwH8P/wAAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB8H/AfwH8B/AfwH8B/AfwH8B/B/8AAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAD4A+AAAAAAOA/gD4A+APgD4A+AP4D+A+YPmP/4AGABgAYAGAAQAEAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAfw/8B/AfwH/B/AfwH8B/AfwH8P/wAAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGAPgAGABgAHABwADAAwADAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAD8A/AAAADAP//8D8w/MPzD8w//Pwz8M/A/w/8AAAAAAAAAAAAAAAAAAAAAAA"
  ],
  "j": [
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB8H/AfwH8B/AfwH8B/AfwH8B/AfwH8H8P4AAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPA/wD8A/APwD8A/APzD8w/DPwz8D/8/P/AAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAGAAQAEAAwCMA/gH4ASADYA+B/wHkB4AeAHgB4AeAHgB4AeAHgB498P8AAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAwADAAwAMADAA/8P/AwAMADPD/wD8A/APwD8A/APwD8A/APwD8A/8/P/AAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHAfwB8AfAHwB8AfAHwB8AfAHwB/Af/fj/gMADAAwACAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAB/wf8AcAAwB/H/AfwH8B/AfwH8B/AfwH8B/AfwH8H8P4AAAAAAAAAAAAAAAAA"
  ],
  "k": [
    "AAAAAAAAAAAAAAAAAAAAAHAPwA8APADwA8APHjxw8cPcD3A+QPHDx78OPD/58EAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAHAPwA8APADwA8APPDzg84PYD2A+gPODzw8cPHv78AAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAABgB4AOADgA4AOADjg4wOMDmA5gPoDjM47OGLhz+8gAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAHAPwA8MPDDww8MPHjxw8ePcj3A+QPHDx48O/D/5/AAIACAAgAAAAAAAAAAAAAAA"
  ],
  "m": [
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA+7j/873O9zvc73O9zvc73O9//8AAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA8+3z/47uO7ju47uO7ju47uO7v/8AAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPbh/8d3Hdx3cd3Hdx3cd3Hdz/8AAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA//v//73+9/vf73+9/vf73O9/////AAAAAAAAAAAAAAAAAAAAA"
  ],
  "n": [
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/gP/AfwH8B/Af8H8B/AfwH8P/wAAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/8AfwH8B/AfwH8B/AfwH8B/B/8AAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA//D949ePPjz48ePHjx48ePH/78AAAAAAAAAAAAAAAAAAAAAAA"
  ],
  "p": [
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/fD548HPBzwc8HPBzwc8ePnj3w8APAP4AAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA+8Dzg4cOHDhw4eOHzh044PODvA4AOAPwAAAAAAAAAAAAAAAAA"
  ],
  "q": [
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB8zx88P+D/g/8P+D/g84PPHx/8APADwB8AAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD2Dng448OPDjw88PPDww8Oeh/oA6AOQH0ABAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD5jz48e8HvD/we8HvB4wePPh/4AeAHgD8AAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB/zx88P+D/g/4P+D/g/4PPHz/8f/ADwA8AfAAAAAAAAAAAAAA"
  ],
  "r": [
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/gB/AfwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/fj28+PPgD4A9gPYDxA8QPEP/wAMAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/8x/Mf8H8B/AfwH8B/AfwH8P/wAAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP8w/MP8D8A/APwD8A/APwz8P/zAAMADAAwAAAAAAAAAAAAAAA"
  ],
  "s": [
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD//4/4H+Bz8AP4Af/A/wP+P//4AAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAH/vx74O+Dj4AfwA/uB7ge+fv/wAAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD//4/4H+Bz8AP4Af/D/wP+D////+AAAAAAAAAAAAAAAAAAAAA"
  ],
  "t": [
    "AAAAAAAAAAAAAAAAAAAAAAAAAAHwB8B/Afw//B/AfwH8B/AfwH8B/AfwH8Af8AAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAADAewHjH4x+P/w34N+A/gP4B+AfgH4B+AfgB8AAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAAA8APAPwD8A//PzD8w/DPwz8M/DPwP8P/Dz/8AAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAAA8APAPwD8A/wPwD8A/wP8D8w/MPzD8P/Dz/wAAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAwA+APgP4D+Y//v4D+A/gP4D+A/gP4D+H/hz/4P+AAAAAAAAAAAAAAAAAAAAA"
  ],
  "u": [
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB8H/AfwH8B/AfwH8B/AfwH8H//nAYAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHw/8B/AfwH8B/D/wH8B/wfw//OYAAAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAPgAHg4H+P/g/4P+D/g/4P+D/g/4P/vz/YAAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHAHw/8B/wf8H/B/MfzH8x/Afw//OYAAAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA4O+fvh74e+Hvh74e+Hvh74e/fz+wAAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA4O+fvh74e+fvn74e+Hvh74e+H//8/gAAAAAAAAAAAAAAAAAAAAA"
  ],
  "v": [
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/j/gc4OODj44OIDyA8gHwB8AcAAAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/PvBww4MODzgcgHoB6APADwA4AAAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/H/g44cOHDxwcQHkB5AHgB4AYAAAAAAAAAAAAAAAAAAAAAAAA"
  ],
  "w": [
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA8+/OPxjM5jGI96PvB7we8HvBwAAAAAAAAAAAAAAAAAAAAAAAA"
  ],
  "x": [
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/zz44OODyAfAHwB+A7g4OOD/78AAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP7x44GOB7APDDww/MZzcO3D/5/AAAAAAAAAAAAAAAAAAAAAAA"
  ],
  "y": [
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/nzwc8HPBw54OGD5gPgD4A+AOADg84P4AAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/vzg44OODg7gOIDyAfAHwB8AcAHA9wP4AAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/z84c+HDhwc4HGB9gHgB4AeAHABwOcD8AAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/nzwc8HPBz54OeD5g/gD4A+APgDgA4P+D+AAAAAAAAAAAAAAA"
  ],
  "z": [
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA//vD7x48cAfAHADwD4c4H+D//4AAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP/jh458OcAPDDgx4D4M8DPDz/4YAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA//vD7x48cAfAHADwD8E+HOB/8//+AAAAAAAAAAAAAAAAAAAAA"
  ]
};
