/**
 * 云南财经大学强智教务系统验证码字符标准排版字模库 (Base64 紧凑编码)
 * 
 * 规格：每个字符对应 14x36 二值矩阵 (504 bits -> 63 字节 -> 84 字符 Base64)
 * 覆盖字符总量：303 个纯净多样性字模 (33 类字符全覆盖)
 * 训练集来源：386 张教务网真实样本 (含 61 张真实难例、250 张盲测基准集与 75 张实时现场样本)
 * 特性：高保真字模，精准区分 h/n/k/m/u/v/1/i 等同形与易混淆字符
 */

export const CANVAS_WIDTH = 14;
export const CANVAS_HEIGHT = 36;

export const PACKED_TEMPLATES: Record<string, string[]> = {
  "1": [
    "AAAAAAAAAAAAAAAAAAAAAAAAHD/wB8AfAHwB8AfAHwB8AfAHwB8AfAHwB8P/8AAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAACADAPzAcAHABwAcAHABwAcAHABwAcAHABwAcAHAP+AAAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAcP/AHwB8AfAHwB8AfAHwB8AfAHwB8AfAHwB8P/8AAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAYD+ADgA4AOADgA4AOADgA4AOADgA4AOADiP/QAEAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAABgH4AOIDh44B+ADgA4AOADgA4AOADgA4AOAf8AAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAACAPgAYAGABgAYAGABgAYAGABgAYAGABgAYAHgP/wADAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAHD/wN8DfAPwD8A/APwB8AfAHwB8AfAHwB8P/8AAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAMAA4AZj+GDgQ4AOADgA4AOADgA4AOADgA4AOADgP/gAAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAEAwv8IPBDwQ8APADwA8APADwA8APADwA8APADwP/wAAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAMD/ADwA8APYD2A9gPEDxA8QPEDwg8IPCDwv/0ABAAQAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAGAfgA4AOADgA4AOADjg4GOAbgA4AOADgA4AOAf8AAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAHD/ww8APADwA8APADwA8APADwA8APADwA8D/8AAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAABgD4AGABgAYAHAxoEZhGERg0YBGARgEYBGAf4EABAAQAMAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAHjB4wACAAgYH+BHgJ4CeAHgB4AeAHgB4AeA/8AAAAAAAAAAAAAAAAAAAAAAA"
  ],
  "2": [
    "AAAAAAAAAAAAAAAAAAAAAAAA/wce/hzwc8HABwAYAeAPAHgBgAwA4McDPAz/8AAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAB/w4e4D/g/4PADwA4AeAfAPADgBgBwM4D+A//8AAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAD4BnAw4OODjgA4AMAHABgAwAIAGADGBhg4YP+AAAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAfwMOGBxwccH4BxAYAOAHAHgBwA4AYMMDHAx/8AAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAPwGODBw4cOHABwAYAOAHADgAwAYAMMGDDgw/8AAEABAAQAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAA/wceMBzwc8HABwAb/eAPAHgBgAwA4McDPAz/8AAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAD8BjgwcOHDhwAcAGADgBwA4AMAGADDBgw4MP/AAAAAAAAAAAAAAAAAAAAAAAA"
  ],
  "3": [
    "AAAAAAAAAAAAAAAAAAAAAAAB/D58+Hvh4AeAHgHwHwAHgA4APAD/g/4P+Hh/AAAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAB+Dx48PPDwA8APAHgPgAPABwAeAHvB7we8PB+AAAAAAAAADAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAA+A5wOODjgA4AOAHAHgAOABgAcAHDhw//OOA+AAAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAADgDMAzAM4AOADAA0A5ADAAQAGABgMYDGAzADgAAAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAPgOcDjg44AOADgBwB4gDmAYcHAxw4cOHDjgPgAAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAPgOcDjs47AOIDiBwh4IDhAYQHEBx4cOHDjgvgAAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAADAAIACfg8cHDhw4AOADgBwD4ADgAYAHABxwccHHDgfgAAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAA/g88PHjx4AeAHgDwD4AHgAYAHABzwc8HPHg/gAAwADAAMAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAfgccHDhw4AOIDuBzT4MDhAYIHCBxwccHHDgfgAAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAMB4h2GcwXMADAAwAYAOAAwAEABgAYHGBxgcwB4AAAAAPgAHwAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAB+Dzw8ePHgB4AeAPAPgA+AHgAcAHPBzwf8eB+AAAAAAAAAAAAAAAAAAAAAAAA"
  ],
  "4": [
    "AAAAAAAAAAAAAAAAAAAQAEAAngJ4B+AZgGYDeBngZ4MeOHj//AfAHgB4AeAf4AAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAHgB4A+AZgGYDGBngZ4MeOHj//AeAHgB4AeAf4AAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAADgAHAAPwAcAPAGwBsAzAZwGcDHBhwf/AHABwAcAHAH8AAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAYAGADgB4AeAFgCYAmAZgMYD/gBgAYAGABgB8AAAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAGAAYAPADsB4w2ANgGYDOAzgY4MOD/8A4AOADgA4A/gAAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAHABwA8AbAGwDMBngZ0MdOHL//AcAHABwAcAfwAAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAYABgYEGADgBoAaAEgCYAmAZgMYD/gBgAYAGABgB+AAAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAACAAgAIDiA4AeANjDYNmAzgP4GODDg//AOADgA4AOAP4AAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAABwAcAPAGwBsATAJwCcBnAxwP/AHABwAcAHAH/AAMAA4ABAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAOADgB4A2ANgGYDOAzgY4MOD/8A4AOADgA4w/gAAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAHABwA8AbAG4DcBnAZxMceHj/+AdAHQBwAcQf0AAAAAAAAAAAAAAAAAAAAAAA"
  ],
  "5": [
    "AAAAAAAAAAAAAAAAAAAAAAAD/84AOADgA4AOADvw8eODwA8AP+D/g/geOHh/wAAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAB/8cAHABwAcAHAB3weeHBwAcAHPBzwcwe/Hg/wAAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAf8GABgMYDGAJgCbwnOFhxAcIHDhw4cMOBjgPwAAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAD/wwAMADAAxgMEDfg54MHAB4Ad8HfBzh4MeB/AAAAAAAAAAAAAAAAAAAAAAAA"
  ],
  "6": [
    "AAAAAAAAAAAAAAAAAAAAAAAAHwHODjg4AMA3AD3wdOHhxwceHHBwwcOGBzgPgAAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAPweePHjwAwA8APPzye/B/AfwH8BzAc8GHng/gAAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAA+A5wccHABgA4AO+Dpw8OODjg44OGDhw2OcR8AAAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAABwA2BZwGDBAOwAdwDWA4wMMDDAwwEMBiANgDwEAAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAA+A5wccHBBgQ4CO+jp08PODrg64OWDlwwOcB8AAAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAABwA2AZgGABAAwANwDWA5gMYDGAxgEYBmANgDgAAAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAABwA2AZgGABAAwANwDWA4gMIDCA0gE4BiAN4DxAAIAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAABAAoAGD4fnFxw/AGADgA74OnDww4MODDgwYMHDA5wHwAAAAAAAAAAAAAAAAAAAAAAA"
  ],
  "7": [
    "AAAAAAAAAAAAAAAAAAAAAAAD//4P4DuBwAcAHAHABwA4AOADgB4AeAHgB4AeAAAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAABD/7wf4HeDgA4AOAGABgAwAMADADwA8APADwA8AAAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAH/DhwwYMMADAAwAYAGADAAwAMAHABwAcAHABwAAAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAD/7we4HODgA4AOAGABgA4AMADADwA8EPBDwA8AAAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAf8OHDBgwwAMADBhgGYAcADAAwAcAHABwAcAHAAAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAD//4P4DuBwAcBHAPADwA4APADwB7AewHiB4AeAAAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAB/88H8BjBwgcEHBDgA4A4AOABgA4AOADgA+AOAAAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAB/88HMBjBwAcAHADgA4AYAGABgA4AOADgA4AOAAAAAOAAfAAAAAAAAAAAAAAA"
  ],
  "8": [
    "AAAAAAAAAAAAAAAAAAAAAAAB/w8e8B/AfwHPBj5wP4HfDx7wH8B/AfwHPHg/gAAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAEAAh/I458HfBzwcOGDzAPgG8Djjwc8HPBzwcOOA+AAAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAB/g4c8DvA7wOODDxgPwG+DhzwO8DvA/wPOHA/AAAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAB/A468HvB7weOGjzIPhG8Tjnwd8HfB3wcOOA+AAAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAADwBmAxgMYHGBZh3QE4BLgWcHGxxicYHGBZgTgAAAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAADAAIACfweOHBxwceHDhg8wD4BvA44cHHBxwccHDjgPgAAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAB/g4c8DvA7wOODDxoPyG+jx7zu8HvA7wOOHQ/AAAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAD8Bxg4cOHDnwcYHngeGNwXGDxw4cOHDhwcYB4AAAAAAAAAAAAAAAAAAAAAAAA"
  ],
  "9": [
    "AAAAAAAAAAAAAAAAAAAAAAAA/g8cPHvAbwH8B/AfwfPPx+cAHAHgB48cPPB+AAAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAEAAgDoBkAZgMYDGAxgMYDGAbgD4AGABgAYBkAbADgAAAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAA/A4YOHPAzwO8DvA7weOfh+4AOAHgB04ZOeB+AAAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAfgcMHDjgY4HOB/gc4PPHx/cQHCDgg4cMHnA/ABgAYABAAQAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAANwAmAJwGKBiAYgGIBmAJgDoACABgAYAkAJADgAAAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAA/A4YOHPAzwO8DvA7weOfh+4AOAHABw4YOeB+AAAAGAAcAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAACAAgAIPhOMTjjwY8HPBxwccPHnw/cIHADgA4OMDnAfAAAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAADAAwACfg8MPDjgY4HOBzgc4PHHw/cAHADgA4cMHHA/AAAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAA8A5gOcPDBwwcMHDBxwO8B7AFwA8AHg5gO4B5AAAAAAAAAAAAAAAAAAAAAAAA"
  ],
  "a": [
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD+Dhw4cAHAfw8cOHPBzwc+fT+4AAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD8Djg44AOAfg84OOPDj44/+j9wAAAGAAAADAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAHgAEAAHgGYBmABgB4B2AZgOYDmA5oHsAAAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAH4HHBxwAcA/B5yccuHLhy89n7oACAAQAEABAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD8Djg44AOAfg84OOPDjw4+ej9wYABwADgAHAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/A44OOgDoH5POTjlw48OPnh/cQAEAAgAIAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAABIABgAGPAWYBmwBgB4B2AZgMYDGA7wH4AAAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAHgGMBjAAwB8BzAYwOMDjA5wH+AAAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD/Dx48eAHgP4+ePHvB7we/Pj+cAAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAH/3GBxgAYA+B5gcYOGDhg84H/AAAAAAAAAAAAAAAAAAAAAAAA"
  ],
  "b": [
    "AAAAAAAAAAAAAAAAAAAAAHAPwA8APADwA8APfD94+HPBzwc8HPBzwc8GPnjPwAAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAD4Az4PxjcAHABwAcAHfB+4eHHBxwccHHBxwccGHjhvwAAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAABgB4AOADgA4AOADvA+4PHDhw4cOHDhw4cOGDzg3zwAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAwA8AHABwAcAHAB3gfeHjfwwfsHDBwwcMHDB5wb4AAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAACGAfgE4AOADgA4AO8D7g8cPHDtw48OHDhw4cPOzfAAAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAH+BgAYAGABgAYAG4BzAYfAGMBg4YOGDDAYwD4AAAAAAAAAAAAAAAAAAAAAAAA"
  ],
  "c": [
    "AAAAAAAAAAAAAAAAAADAAOAAAADgAEAAAAAB/Dx48e+HvgD4A+APgM8DPDgfwAAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB/Dx48e+HvgD4A+APgM8DPDgfwAAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHgHMBzA+wOYDhw4DuGFxgcQB4AAAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB/Dx48e+HvgD8A/APwM8DPDgfwCAAgAIACAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAMAA4ABgAGAAQAAAAD8Dng548ePADwA8APAw4MOGA/AAAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAADAAwACAAgAEABAAIAC/A44OOHDhwAcAHABwMODDhgPwAAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAADAAIACAAgAAAAAAAAA/B54eePHjwA8APADwMeDHhgPwAAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAQAcADAAwAMADOA2wNsDzA8APADwA8YNmDZAzgIH8AAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB/Dx48e+HvgD4A+APg88PPDgfwAMADAAwAMAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/A44OOHDhwAcAHABwMODDhgPwAA4AB4AB4AAAAAAAAAAAAAA"
  ],
  "d": [
    "AAAAAAAAAAAAAAAAAAAAAABgH4AeAHgB4AGH5jz48e8HvB7we8HvB4wePPx+QAAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAIAHAPoA6AOQDgAYH2Dng448OPDjw48OPDgw4OfB9AAAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAABAAQYEeBDgQ4EOBBgfYHeBzg44OODjo46OORjkd8j0IABAAQAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAABgD4AOADgA4AGB9g54OOHDvw4fuHDhw4MODnwfQAAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAA/+wBsD4gOADgA4AGB9g54OOHDhw4cOHDhw4MODnwfQAAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAABgD4AOADgA4AGB9g54OOHDhw4cO3Djw4sOHnxfQAABAAQACAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAMAfABwAcAHAAwPsHPBxw4cOHDhw4cOHBhwc+D6AAAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAgA4AGABgAYACAOg24FmBxgcYHGAx4MZxGDbgDgAAAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAABgH4AOADgA4AGD9vx4cOPjjn44OODjg4YOHHw/QAAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAYAeABgAYAGABgP4HOBxg4YOGDhg4YOGBhgc8D8AAAAAAAAAwAAAAAAAAAAAAAA"
  ],
  "e": [
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB/Dx48O+D/g///+APgA8DPDgfwAAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAfAc4HG/hw+cP/DgA4AHDBxgHwAAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAQD4DnA4w8OPDj/48APAA4YOMA+AAAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHA2YNmD5g+YP+D4A+ANiDZgx4MBwADAAIAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAADgAGAAYABwADAAAAAA/A44OGHBxwcf/HABwAODDhgPwAAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/A44OGHBxwcf/HABwAODDhgPwAAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/B54eGPBzwc///ADwAeDHhgPwBAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAACAAgAEABAAAAAAfAc4HGDhw4cP/DgA4AHDBxgHwAA//gAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA8AZgGIDDAwzv8HwAzgGMBiAPAAAAAAAAAAAAAAAAAAAAAAAA"
  ],
  "f": [
    "AAAAAAAAAAAAAAAAAAAAAAAAH4DnDxw8APA//A8APADwA8APADwA8APADwD/wAAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAD4B3A5wOADgH/AOADgA4AODDgM4AOADgA4A/wAAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAD4B3A5wOADgH/AOADgA4AOADgA4AOADgA4M/wwADAAMAAwAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAfAO4HOBwAcA/4BwAcAPABwAcAHgB2AcAHAH+YABAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAPwHuDjg4AOA/+A4AOADgA4AOADgA4AOAD8D/8AAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAPwHuDjg4AOA/+A4AOADgA4AOQDkA4gOIDhD/wACAAgAIABAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAPgHcD3A4AOQ/8A4gOIDgA4IOCDgQ4AOADgD/AAAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAA4MbBMwTAEwB/ATAEwxMDzAEwBMATAEwBMAXwEAAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAHgDcBnAYAGAP8AYAGABgAYAGABhMYQGCBgh/EABAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAPgHcDnA4AOA/8A4AOADgA4APADsA4AOADgz/AAAAAAAAAAAAAAAAAAAAAAAA"
  ],
  "g": [
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD/x7s88PPDzwe8H+DwA/4PfvB7we/Ph/gAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD/h3Y58OeDnkd5H8DgA/wO/PBzwc+fB/AAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAMADAAIACAAgAIABAD/x/s88PPDzwe8H+DwA/4PfvB7we/Ph/gAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAQAED+g1rZiP4hmENhDwRgAfAG8DHAxwOcA8AAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAH+Dthzgc4HOA7gPwHDx/Dd8OHDhw88D8AAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAgAGAAYAAfwO0HOBzgc4DuA/AcAH8B3w4cOHDzwPwAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADAH/DUNmAZgGYA2APgGIB+AbgOYDmA5gDwAAAAAAAAAAAAAAAAA"
  ],
  "h": [
    "AAAAAAAAAAAAAAAAAAAAAHAPwA8APADwA8APfD548ePHjx48ePHjx48ePHv78AAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAABgB4AOADgA4AOADvA84OODjg44OODjg44OOHjh98IACAAQAEAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAABgB4AOADgA4AOADvA84OODjg44OODjg44OODjh9/wADgAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAwAAAAAAA9wHmBxgcYHGBxscYHGBxgcYPvAAAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAABgB4AOADgA4AOADvA84OODjg44OODjg47OOzjj98gAIABAAQAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAACAAYAGAAAAA/fT588ePHjx48ePHjx48ePHv78AAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAEABAAAAAAAAAAAA/fD548ePHjx48ePHjx48ePHv78AAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAMAPABwAcBHARwCd4nnFxxccXHBxwccHHBxwccPvgAAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAMAPABwAcAHABwAd+H3d44cOHDhw4cOHDhwwecG+AAAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAGAPgA4AOADgA4AO8Dzg44OODjg44OODng44OOP3wAEAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAGAPgA4AOADgA4AO+Dxw4cOHDhw4cOHDhw4cOHP34ACAAgAEABAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAGAPgA4AOADgA4QOfDng50O5DuI9iOcTnk4YOHP34AAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAMAPABwAcAHABwAd4H3R48cOnDpw6cOnDlwxecW+EAAAAAAAAAAAAAAAAAAAAAAA"
  ],
  "i": [
    "AAAAAAAAAAAAAAAAAAAAAAAAfAHwAMADAB4/+AfgH2B9gfAHwB8AfAHwB8P/8AAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAfAHwAAAAABw/8AfAHwB8AfAHwB8AfAHwB8P/8AAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAfAHwAAAAABw/8AfAHwB8AfAHwB+AfgH2B9v/8ABAAQAEABAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAA4AOAAAAAAGA/gA4AOADgA4AOADgA4AOADhP/wACAAgAEABAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAADAAwABAAAAQA8gDIAxAMQDAAwAMADAAwAMAPwAAAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAADgA4EABAAIYD+AjgE4BOMTg04DuALgC4AeAf8AAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAPAAOAfcHwAAAAABw/8AfAHwB8AfAHwB8AfAHwB8P/8AAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAADAAwAAAAAAQA8ADAAwAMADAAwAMADfgwAMAPwAAAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAeAHgAAAAADg/4AeAHgB4AeAHgB4AeAHgB4P/4ACAAgAEABAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAfAHwAAAAABw/8AfAHwB8AfAHwB8AfA3wN8P/8wAMADAAwAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAADAAwAAAAAATA8MDAAwAMADAAwAMADAAwAMAPwAAAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAHgB4AAAAAA4H+AHgB4AeAHgB4AeAHgB4EeB/8MAAAAAAAAAAAAAAAAAAAAAA"
  ],
  "j": [
    "AAAAAAAAAAAAAAAAAAAAAAAAH8B/AAAAAAHD/wB8AfAHwB8AfAHwB8AfAHwB8Af/fj/gAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAA8APwACAAgDEfxAcIHCBwAcCHAhwGcBnAFwBcAPB7gPwAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAYQBEAfwD8AbABIAeH/wH0B8AfAHwB8AfAHwB8AfAHwB8+8D+AAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAACAAgAP8D/AYAGABnD/wB8AfAHwB8AfAHwB8AfAHwB8Af/fj/gAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAD8A/AAAAAAHB/wA8APADwA8APADwA/APwDzA8wPPvg/gGAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAPwD8AEAAwAeH/QHwB8AfAHwB8AfAHwB8AfAHwB8+8D+AAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAADAAwAMD/A/wADAAwHN/wA8APADwA8APADwA8APADwA8APPvg/gAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAYAH8B/AGABgAfD/wB8AfAHwB8AfAHwB8AfAHwB8Af/fj/gAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAeAHgAAAAABgH4AOADgA4AOADgA4AOAHgA4AOADw9wD4AAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAA8APAAAAAADAfwAfAHwByAcgHEBxAcIHCBwQcAHB7gPwAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAMADH8N/zAMwAyHP/wx8CfAnwH8AfAHwB8AfAHwB8Af/fj/gAAAAAAAAAAAAAAAA"
  ],
  "k": [
    "AAAAAAAAAAAAAAAAAAAAAHAPwA8APADwA8APPjzg84PYD2A+gPODzz8cPHv78MAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAABgB4AOADgA4AOADng5gOYDsA7APQDmA5wOMDjh98AAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAMAPABwAcAHABwAc4HIByAdgHYB6AcgHMBxAcYPvABgAGAAYABAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAHAPwA8APBDwQ8CPPjzo86PYT2E+hPODzw8cPHv78AAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAABgB4AOADgA4AOADng5gOYDsM7DPQzmM5zOMLjj98gAIACAAgAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAHAPwA8APADwA8APPjzg84PYD2A+gPuD3w88PHv78AEAAAAEABAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAADADwAcAHABwAcAHHhxgcYHcB3AeQHGBxz8MHDj58AAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAQDEDxAcIHCBwgcIHHhxgccHdB3QeQHGNxzcMPDj58gAEABAAQAAAAAAAAAAAAAAA"
  ],
  "m": [
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA+3D/47uO7ju47uO7ju47uO7v/8AAAAAAD/AAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA+3D/47uO7ju47uO7ju47uO7v/88AA8AAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAwADg/fH/N/wf8H/B/wf8H/B/wf8P/gAAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/YH/h/2f8X/B/wf8H/B/wf8P/gAAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAgAGAAAAAAAQAAAA9uH/x3cd3Hdx3cd3Hdx3cd3P/4AAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAQAEAAAAEABA+/D/47uO7ju47uO7ju47uO7v/8AAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA+3D/47uO7ju47uO7jv47+O7v/8AEAAgAIABAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAACAAQAEAAAAAAAAAAAe3D/47uO7ju47uO7ju47uO7n/8AAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAH7g/8P3D9w/cP3D9w/cP3D9x/8AA4ABgAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAgAIABAAQACAAgAe3D/47uO7j+4/uO7ju47uO7n/8AAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPbh/8d3Hdx3cd3Hdx3cd3Hdz/8AAAAAAAAAAAAAAAAAAAAAAA"
  ],
  "n": [
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/fD748ePHjx48fPHjx48ePHv78AAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAADgAAAAAAAAPfB44cOHDhw4cOHDhw4cOHDj58AAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAADAAwAMADAAwAMADAA/fP578e/Hvx78e/Hjx48ePHv78AAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/8D7g64OeDng44OODjg44OPP3wACAAgAEAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHvA84OODjg44OODjg44OODjh98AAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA9wHmBxgcYHGBxgcYHGBxgcYPvAAAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAHAPwA8APADwA8APfD548ePHjx48ePHjx48ePHv78AAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAADgAAAAwADAAAAAAA++Dxw4cOHDhw4cOHDhw4cOHP34AAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIACAAbADYAmAJgCYAmAJgCYAmAJgHYAAAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAACAAgAEABAAIAC+8Tzk44OODjg44OODjg44OOP3wAAAAAAAAAAAAAAAAAAAAAAA"
  ],
  "p": [
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/fD548HPBzwc8HPBzwc8ePnj3w8APAP8AAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA7gHMBjgY4GOBjgY4GOBjQczG4JgBYAPgAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPfB44cHHBxwf8HHBx4ccOHjh3wcAHAD+AAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA7gHYBjAYwGMBjgY/GNJmIdgG4BgDYAPgAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA++Dxw4OODjg44OODjg44cPHDvg4fOAP4AAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHvA84OHDhw4cOHDhw4cOODzg7wOADgB+AAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAACAAQAEAAgAIABAAAAA/wdsOcDnA5wHcB+A4AP4Dvhw4cOHngfgAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAABANoBtgREEQhEERAEQBEDTAGwBYEQAEADwAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD+A5gOMDjA4wOMDjA4wOYDnA/sOADgA8AAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA94HnB44duHHhw4cPnDlxwecHeBwAcAPwAAAAAAAAAAAAAAAAA"
  ],
  "q": [
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD5jz48e8HvB78e8nvB4wePPh/4AeAHgH8AAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD2Dng448OPDjw88PPDww8Oeh/oA6AOQP0ABAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAOh24NmDxgc/nGBxgcYFGBbgT4EGABgA4AAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA49h54OOHDhw4cOHDhw4MODngf4AOADgD8AAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAPAAAAAAAAAAAAAAD7Dnw4c8HPBzwc8HPBwwcOfB/wAcAHAP4AAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAADAAwACAAgAEABAAMAD5jz48e8HvB7we8HvB4wePPh/4AeAHgH8AAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB9vx4cOODjg44OODjg4YOHHg/4AOADgH8AAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAACAAcAA8AAwAAAAAAAAewc8HHDhw4cOHDhw4cGHBzwP8AHABwB8AAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHvA84OH/hw4cOHDhw4cOODzg7wOADgB+AAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAABAAMAAgAEAAwACOgG4BmAxgMYDGAxgMYBGAbgD4AGABgA8AAAAAAAAAAAAAAAAA"
  ],
  "r": [
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/ng5cPnDgA4AOADgA4AOADgP/gAAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/ng5cPnD4A+AOQDkA4gOIDiP/wAEAAgAIAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/ng5cPnDgA4AOALgC4AuALgP/ggAEABAAQAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAEAAgAIAAAAI+6BvAd0GBBgAYAGABgAYAGAP4AAAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/eB1wecHAByAcQHEBwgcIHBP+QACAAgAEABAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADwAP3gdcHnBwAcAHABwAcAHABwD/gAAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAQ/ng58PvDiA4gOEDhA4QOEDhP/oACAAgAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP3gdcHnBwAcAHABwAcAHABwP/jAAIACAAAAAAAAAAAAAAAAAA"
  ],
  "s": [
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD//4/4H+Bz8AP4Af/A/wP+P//4AAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAIABAAQAEAAgAIABH+fnjwY8GDwAfgB+OHjh48+P/AAAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB/z488DPAx+DH8Ifzg84PPHz/4CAAAABAAQAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD//4/4H+Bz8AP4Af/A/wP+f//4BAAMADAAwAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB/h44cGHBg+D//B/hg4YOHHh/wAAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP4PODhg4YHgA+AD4M//Dg54P8AAAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/w+cODDgwfAD8AHwwcMHDjw/4AAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPA+wPHjxH3AM4DHA8wPMDzA/wMADAAwAMAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAH+Pvjx48GDwAfgB+OHjh48+P/AAAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAH/vx74O+Dj4AfwA/uB7gf+f//0ABAAQAEABAAAAAAAAAAAAAA"
  ],
  "t": [
    "AAAAAAAAAAAAAAAAAAAAAAAAAADgA4AeAHg//geAHgB4AeAHgB4AeAHjB4wP4AAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAADDgI4CeAfg//geAHgB4AeAHgB4AeAHjB4wP4AAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAADAAIACAAQwEMAnAJwD/gXAFwA8APABwAcAHABzAcwD4AAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAAADAAwA8APA//A9gPYDxA8QPEDxA8IPGDxgP4ABAAQAEAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAAABwAcAPADwH/gPADwA8APADwA8APADzA8wH4AAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAwAMAHABwD/gHABwAcAHABwAcAHABzAcwD4AAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAAAGABgA4AOA/8A4AOADgA4AOADgA4AOYDmAfAAAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAAADgA4AeAHg//geAHgB8AfAHsB7AewHjB4wP4ABAAQAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAAADAAwA8APA//A8APADwA8APADwA8APGDxgPwAAAAAAEABAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAQAEAAwDsA4geIHi//weEHgB4AeAHgB4AeAHjB4wP4AAAAAAAAAAAAAAAAAAAAAAA"
  ],
  "u": [
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAcG/Pjx48ePHjx78ePHjx48ePvx+QAgAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAww88HHBxwecHHBzwccHHhx2e+T6AAAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGGHng44OODjg47OOzji44uOD3wfQAAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAADgAHgAHgMGPHhw4cOHDhw4cOHDhw4cOHnw/QAAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAADAAwAMADMGPHjw48OPDjw48OHDhw4cOHnw/QAAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAABAAQACAAgYY+eDjw48OPDjo46OOjjo45PfR9AAAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAww88HHhx4cdHHRxyccnHFxxe+D6AAAAAAAAAAAAAAAAAAAAAAAA"
  ],
  "v": [
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/nzwYccHHB5wOYD2A9gDgA4AMAAAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/HjgwYYGGBxgMQDkg5IHiB4gYIABAAQAEABAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHzw4YGMBjAcwDIA6AOgBwAcAGAAAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAIACAAY/nzx4ccHHB5wOaD2g9gDgA4AMAAAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAwACAAQAD9wGIAmAJgDYAUAHABwAYAGABgAAAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAEAAgAIABAAQAAAA/HjgwYYGGBxgMQDkA5AHgB4AYAAAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHz44ZGMRjCcwjIE6BOgBwAcAGAAAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/Hjg0YZGGRxkMRDkQ5AHgB4AYAAAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAwAC/HzgwYYGGBxgMQDkA5AHgB4AYAAAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAI+cHGAxAMQDkAYAHABwAOADgAwAAAAAAAAAAAAAAAAAAAAAAAA"
  ],
  "w": [
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA+9zuY5mG7BmQd0HuA7gO4DuAwAAAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAgAIACAAfe13MczDdgzIO6D3AdwHcB3AYAAAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAQACAAg9/ncxzMN3DMg7pPcR3AdwHcBgAAAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPex3MczDdszIO6D3AdwHcB3AYAAAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA93HbhyYNuDJA7QPYB2AdgHYBgAAAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAgAHAAQADAAwAEAB7YW0FtBLgSwE8BNgTYE2BNgDAAAAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAH+w/MOzB9vbIO6B/ANwDcA3AIAAAAAAAAAAAAAAAAAAAAAAAA"
  ],
  "x": [
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAcAAwAAAAP4BoAKADgAwAMADgAoASAEwDuAAAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP3x5wOcD2AOADgA+A7gccHHv78AAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP3x5zOcz2MODDgw+M7jcc3Hv7/AAwAMADAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAgAIABAAQAEAAgAJ9xOYRmCdAjgA4APAGwDGAxw+8AAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD7wcwDMA6AHABwAeANgGMBjh98AAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAADAAwACAAgAIACAAQAH7w4wGMB6APADwA+AZgMMDDj58AAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAdwzQM0DNMRg0YDHATwAkAJgP8AAAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAdgDQA0ANABgAYAHwDzgkAJgP4AAAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAGAAQAAAAAAAAAAAfeDmAZgHQA4AOADwBsAxgMcPvgAAAAAAAAAAAAAAAAAAAAAAA"
  ],
  "y": [
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/vxxwccHHA7gOYD2AOADgA4AMADAMwD4AAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAACAAQAAAAAAAAAAA/fhhgYYGGA3AMQDkAeAHgB4AYAGANgDwAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/vxxwccHHA7gOYD2AOA/+A4AMADAMwD4AAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/wCQAlAJMDww0DNABgAYAGABAAQAUAHAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAH3wYwGMBjANgDIA6AHABwAcAGABgDYA8AAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/nywwcMDDAZgGIB6APADwA8AOADgG4B4AAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/gCQAlAJIDxg0ENAxgEYBGABAAQAUAHAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAMAAwADAAMAAwAD/fBjAYwGMA2AMgDoAcAHABwAYAGANgDwAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAADAAAADAAAAA/8DMAzAMwB4AaAGgAwAMADAAgAIAaAHgAAAAAAAAAAAAAAAAA"
  ],
  "z": [
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA//vD7x48cAfAHADwD4c4H+D//4AAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD/sw7McLGCHgRwE8A+MODDhw/4EAAgAIAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAHAAMAA8AAwAAAA/+OHjjg4wA8AOAHgDxwwc8PP/gAAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD/gw4McDGAHgBwA8OeMeDDhw/4AAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAQAEAAwAMADAAIAC//eH3jw44AeAGAHgDw44O+Hv/wAAAAAAAAAAAAAAAAAAAAAAA",
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAcAA8AA/gMYDOAzABwAYAOAHEBhA4wP4AAAAAAAAAAAAAAAAAAAAAAAA"
  ]
};
